FROM node:20-alpine AS builder
WORKDIR /workspace
COPY package.json package-lock.json tsconfig.base.json ./
COPY apps/frontend/package.json apps/frontend/package.json
RUN npm install
COPY apps/frontend ./apps/frontend
RUN npm run build --workspace apps/frontend

FROM nginx:stable-alpine AS runner
COPY --from=builder /workspace/apps/frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
